### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by anju-infracloud** [vangaakhila/URL_Shortener#1]
when I made a request `curl -X POST -H "Content-Type: application/json" http://localhost:8080/ -F "url=facebook.com"` it failed with following error

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/URL_Shortener/app.py", line 27, in home
    url = input["url"]
  File "/usr/local/lib/python3.9/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'url'`

Also, can you please improve code with following changes:
1. accept data as a standard input for curl.
curl -X POST -H "Content-Type: application/json" http://localhost:8080/ -d '{"url": "facebook.com"}'
2. Implement `create_short_url` endpoint to shorten URL

**Comment by vangaakhila** [comment]
`curl` -X POST -H "Content-Type: application/json" http://localhost:8080/ -F "url=facebook.com", for my understanding -F is for providing form data and as -H "Content-Type: application/json" is given, hence the program failed.

> Although, I have made the requested changes to include both form data and application/json data.

1) curl -X POST -H "Content-Type: application/json" http://localhost:8080/create_short_url -d '{"url": "google.com"}':
```
<html>
<body>
   <div>
      Your shortened URL is: <a href="http://localhost:8080/short_url/2"> http://localhost:8080/short_url/2</a>
   </div>
</body>
</html>
```
2) curl -L -X POST "http://localhost:8080/create_short_url" -F 'url="akhila"'
```
<html>
<body>
   <div>
      Your shortened URL is: <a href="http://localhost:8080/short_url/4"> http://localhost:8080/short_url/4</a>
   </div>
</body>
</html>
```

**Comment by anju-infracloud** [comment]
$ curl -X POST -H "Content-Type: application/json" http://localhost:8080/create_short_url -d '{"url": "google.com"}'
```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>```

**Comment by vangaakhila** [comment]
Just a question, have you pulled the latest docker image before execution. As I verified the program in multiple other machines, its working fine.
